version: "2"
services:
    zeppelin:
        image: dylanmei/zeppelin
        container_name: zeppelin
        environment:
            ZEPPELIN_PORT: 8080
            ZEPPELIN_JAVA_OPTS: >-
                -Dspark.driver.memory=1g
                -Dspark.executor.memory=2g
            SPARK_SUBMIT_OPTIONS: >-
                --conf spark.driver.host=localhost
                --conf spark.driver.port=8081
                --conf spark.es.nodes=elasticsearch
                --conf spark.es.discovery=false
                --conf spark.es.port=9200
                --packages org.elasticsearch:elasticsearch-spark-20_2.11:5.0.0-alpha5
            MASTER: local[*]
            ELASTICSEARCH_HOST: 10.1.214.168
            ELASTICSEARCH_PORT: 9300
            ELASTICSEARCH_CLUSTER_NAME: trs-qa-es
            ELASTICSEARCH_BASICAUTH_USERNAME: elastic
            ELASTICSEARCH_BASICAUTH_PASSWORD: ixqaes
        ports:
            - 8080:8080
            - 8081:8081
            #- 4040:4040
        volumes:
            - ./notebooks:/usr/zeppelin/notebook
        networks:
            zeppelin_net:
                aliases:
                    - zeppelin
    nginx:
        image: nginx
        container_name: nginx
        networks:
            zeppelin_net:
                aliases:
                    - nginx
        ports:
            - "9200:9200"
        environment:
            - "EXPOSE_PORT=9200"
            - "TARGET_HOST=https://localhost:9200"
        volumes:
            - .:/app
        command: /app/install.sh

networks:
    zeppelin_net:
